In [2]:
import numpy as np

arr = np.array([11,22,33,44,55])

print("Mean :",np.mean(arr))
print("standard deviation:",np.std(arr))

Mean : 33.0
standard deviation: 15.556349186104045


In [21]:
import numpy as np

matrix = np.random.randint(1, 50, size=(5, 5))

print("Random Matrix:")
print(matrix)
min_row_values = np.min(matrix, axis=1)
max_row_values = np.max(matrix, axis=1)

print("\nMinimum values along each row:")
print(min_row_values)
print("Maximum values along each row:")
print(max_row_values)

min_col_values = np.min(matrix, axis=0)
max_col_values = np.max(matrix, axis=0)

print("\nMinimum values along each column:")
print(min_col_values)
print("Maximum values along each column:")
print(max_col_values)

Random Matrix:
[[27 41 39 11 30]
 [49 35 44 36 33]
 [32 36 27 46 21]
 [21 11 10 42 29]
 [40 37 44  7 16]]

Minimum values along each row:
[11 33 21 10  7]
Maximum values along each row:
[41 49 46 42 44]

Minimum values along each column:
[21 11 10  7 16]
Maximum values along each column:
[49 41 44 46 33]


In [22]:
import numpy as np

def cosine_similarity(a, b):
    dot_product = np.dot(a, b)
    norm_a = np.linalg.norm(a)
    norm_b = np.linalg.norm(b)
    similarity = dot_product / (norm_a * norm_b)
    return similarity

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

print("Cosine Similarity:", cosine_similarity(vector1, vector2))


Cosine Similarity: 0.9746318461970762
